apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tenant.yaml
configurations:
  - config.yaml
secretGenerator:
  - name: minio-creds-secret
    literals:
      - accesskey=minio
      - secretkey=minio123
