## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: arian
spec:
  image: minio/minio:RELEASE.2020-10-18T21-54-12Z
  podManagementPolicy: Parallel
  credsSecret:
    name: minio-creds-secret
  ## Specification for MinIO Zone(s) in this Tenant.
  # once a zone has been allocated, it is immutable. If you want to expand
  # storage; create a new zone New zones must have the same or better SLA than
  # other zones in this list.
  zones:
    - servers: 4
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: "local-path"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  