apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        env:
          - name: SERVICES
            value: sqs,sns,dynamodb
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
        ports:
        - name: localstack
          containerPort: 4566
