
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - deployment.yaml
 - ingress.yaml
configMapGenerator:
  - name: brig-config
    files:
      - "config.yaml"
secretGenerator:
  - name: brig-secret
    files: []
